const canciones = [
    {
        tema: "El CLúB",
        videoclip: "BAD BUNNY - EL CLúB (Video Oficial).mp4",
        lyrics: "Bad Bunny - El CluB (LetraLyrics).mp4",
        audio: "ElClub.mp3",
        img: "bad_bunny_el_club-portada.jpg",
        segon_inici: 0.11,
        segon_final: 5.53,
    },
    {
        tema: "Moscow Mule",
        videoclip: "Bad Bunny - Moscow Mule (Video Oficial).mp4",
        lyrics: "Bad Bunny - Moscow Mule (La Letra  Lyrics).mp4",
        audio: "MoscowMule.mp3",
        img: "bad_bunny_un_verano_sin_ti-portada.jpg",
        segon_inici: 0.0,
        segon_final: 4.0,
    },
    {
        tema: "Mónaco",
        videoclip: "BAD BUNNY - MONACO (Official Video).mp4",
        lyrics: "Monaco.mp4",
        audio: "Monaco.mp3",
        img: "MONACO.jpg",
        segon_inici: 0.30,
        segon_final: 4.55,
    },
    {
        tema: "Amorfoda",
        videoclip: "BAD BUNNY - AMORFODA (Video Oficial).mp4",
        lyrics: "Bad Bunny - Amorfoda (Lyrics).mp4",
        audio: "Amorfoda.mp3",
        img: "amorfoda-portada.jpg",
        segon_inici: 0.23,
        segon_final: 2.52,
    },
    {
        tema: "La Jumpa",
        videoclip: "Arcangel, Bad Bunny - La Jumpa (Video Oficial).mp4",
        lyrics: "Arcangel, Bad Bunny - La Jumpa.mp4",
        audio: "LaJumpa.mp3",
        img: "La-Jumpa.jpg",
        segon_inici: 0.0,
        segon_final: 4.12,
    },
    {
        tema: "Tu no vive asi",
        videoclip: "Arcangel x Bad Bunny X Dj Luian X Mambo Kingz - Tu No Vive Asi [Video oficial].mp4",
        lyrics: "Tu no vive asi- Bad Bunny ft Arcangel (letra).mp4",
        audio: "TuNoViveAsi.mp3",
        img: "tu no vive asi.jpg",
        segon_inici: 0.09,
        segon_final: 4.30,
    },
];

